name: Package VSCode Extension

on:
  push:
    branches:
      - main
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v5

      - name: Setup Node
        uses: actions/setup-node@v5
        with:
          node-version: 20

      - name: Install vsce
        run: npm install -g @vscode/vsce

      - name: Install dependencies
        run: npm install

      - name: Package extension
        run: vsce package

      - name: Upload VSIX
        uses: actions/upload-artifact@v4
        with:
          name: vsix
          path: "*.vsix"
