name: Package VSCode Extension

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-node@v5
        with:
          node-version: 20

      - run: npm install -g @vscode/vsce

      - run: vsce package

      - run: |
          mkdir -p bin
          rm -f bin/*.vsix
          mv *.vsix bin/

      - run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add bin/*.vsix
          git commit -m "Update VSIX" || echo "No changes"
          git push
